Try to fix Python 3.4 builds on Travis CI
Adding the 'pip install --upgrade' option in dd53b9eef6e fixed the
Python 2.6 job on Travis CI but caused the Python 3.4 job to start
failing with an obscure error related to pkg_resources.

Searching for parts of that error message indicate that upgrading
pip and/or setuptools may help to resolve the problem.

Here's the failing job:
https://travis-ci.org/xolox/python-humanfriendly/builds/496657455

And below follows the (relevant) part of the output:

$ scripts/travis.sh pip install --constraint=constraints.txt --requirement=requirements-travis.txt --upgrade
...
Installing collected packages: six, scandir, pathlib2, more-itertools, setuptools, attrs, pluggy, py, atomicwrites, pytest, coverage, pytest-cov, pycodestyle, typing, mccabe, entrypoints, pyflakes, flake8, snowballstemmer, pydocstyle, flake8-polyfill, flake8-docstrings, humanfriendly, capturer, coloredlogs, docopt, urllib3, certifi, chardet, idna, requests, coveralls
  Found existing installation: six 1.10.0
    Uninstalling six-1.10.0:
      Successfully uninstalled six-1.10.0
  Rolling back uninstall of six

Exception:
Traceback (most recent call last):
  File "$VIRTUAL_ENV/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2813, in _dep_map
    return self.__dep_map
  File "$VIRTUAL_ENV/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2624, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "$VIRTUAL_ENV/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2804, in _parsed_pkg_info
    return self._pkg_info
  File "$VIRTUAL_ENV/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2624, in __getattr__
    raise AttributeError(attr)
AttributeError: _pkg_info

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "$VIRTUAL_ENV/lib/python3.4/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "$VIRTUAL_ENV/lib/python3.4/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "$VIRTUAL_ENV/lib/python3.4/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "$VIRTUAL_ENV/lib/python3.4/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "$VIRTUAL_ENV/lib/python3.4/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "$VIRTUAL_ENV/lib/python3.4/site-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "$VIRTUAL_ENV/lib/python3.4/site-packages/pip/locations.py", line 140, in distutils_scheme
    d = Distribution(dist_args)
  File "$VIRTUAL_ENV/lib/python3.4/site-packages/setuptools/dist.py", line 321, in __init__
    _Distribution.__init__(self, attrs)
  File "/opt/python/3.4.6/lib/python3.4/distutils/dist.py", line 280, in __init__
    self.finalize_options()
  File "$VIRTUAL_ENV/lib/python3.4/site-packages/setuptools/dist.py", line 389, in finalize_options
    ep.require(installer=self.fetch_build_egg)
  File "$VIRTUAL_ENV/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2324, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "$VIRTUAL_ENV/lib/python3.4/site-packages/pkg_resources/__init__.py", line 862, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "$VIRTUAL_ENV/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2568, in requires
    dm = self._dep_map
  File "$VIRTUAL_ENV/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2815, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "$VIRTUAL_ENV/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2824, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "$VIRTUAL_ENV/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2806, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "$VIRTUAL_ENV/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1468, in get_metadata
    value = self._get(self._fn(self.egg_info, name))
  File "$VIRTUAL_ENV/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1577, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '$VIRTUAL_ENV/lib/python3.4/site-packages/six-1.10.0.dist-info/METADATA'