Fix Python 3 incompatibility (distutils.spawn)
Much to my dismay this morning I ran into the following breakage on a
Python 3.6 installation based on native Debian /  Ubuntu packages:

  Traceback (most recent call last):
    File "...", line 1, in <module>
      from coloredlogs.syslog import enable_system_logging
    File ".../coloredlogs/__init__.py", line 138, in <module>
      from humanfriendly import coerce_boolean
    File ".../humanfriendly/__init__.py", line 25, in <module>
      from humanfriendly.tables import format_pretty_table as format_table
    File ".../humanfriendly/tables.py", line 32, in <module>
      from humanfriendly.terminal import (
    File ".../humanfriendly/terminal.py", line 26, in <module>
      import distutils.spawn
  ModuleNotFoundError: No module named 'distutils.spawn'

To enable local development and testing against lots of Python releases
I use the "deadsnakes" package repository to install 2.7, 3.4, 3.5, 3.6,
3.7 and 3.8 at the same time. Before committing 335a69bae5 I did check
the availability of the distutils.spawn module:

peter@peter-mbp> ls -l /usr/lib/python*/distutils/spawn.py
-rw-r--r-- 1 root root 8,5K nov  7 11:07 /usr/lib/python2.7/distutils/spawn.py
-rw-r--r-- 1 root root 7,4K mrt 29  2019 /usr/lib/python3.4/distutils/spawn.py
-rw-r--r-- 1 root root 7,3K nov 24 02:35 /usr/lib/python3.5/distutils/spawn.py
-rw-r--r-- 1 root root 7,3K okt 28 17:30 /usr/lib/python3.6/distutils/spawn.py
-rw-r--r-- 1 root root 7,7K okt 28 17:30 /usr/lib/python3.7/distutils/spawn.py
-rw-r--r-- 1 root root 7,7K okt 28 17:30 /usr/lib/python3.8/distutils/spawn.py

I took this to mean it would be available on all these versions. Clearly
I was wrong and this broke Python 3 compatibility. This new commit
should fix the issue by using shutil.which() on Python 3 instead.